@startuml
class bitronix.tm.BitronixTransactionManager
class com.fasterxml.jackson.databind.ObjectMapper
class com.rabbitmq.jms.admin.RMQConnectionFactory
class com.rabbitmq.jms.admin.RMQDestination
class jakarta.jms.Connection
class jakarta.jms.ConnectionFactory
class jakarta.jms.JMSException
class jakarta.jms.Message
class jakarta.jms.MessageConsumer
class jakarta.jms.MessageProducer
class jakarta.jms.Queue
class jakarta.jms.Session
class jakarta.jms.TextMessage
class jakarta.persistence.EntityNotFoundException
class jakarta.persistence.GenerationType
class jakarta.servlet.FilterChain
class jakarta.servlet.ServletException
class jakarta.servlet.http.HttpServletRequest
class jakarta.servlet.http.HttpServletResponse
class jakarta.transaction.SystemException
class jakarta.transaction.UserTransaction
class jakarta.ws.rs.container.ContainerRequestContext
class jakarta.ws.rs.container.ContainerResponseContext
class java.io.IOException
class java.security.NoSuchAlgorithmException
class java.sql.Date
class java.time.LocalDateTime
class java.time.format.DateTimeFormatter
class java.util.ArrayList
class java.util.Collection
class java.util.HashMap
class java.util.HashSet
class java.util.List
class java.util.Map
class java.util.Objects
class java.util.Optional
class java.util.Set
class java.util.logging.FileHandler
class java.util.logging.Level
class java.util.logging.Logger
class javax.naming.Context
class javax.naming.InitialContext
class javax.naming.NamingException
class javax.transaction.SystemException
class org.apache.commons.codec.binary.Base64
class org.apache.commons.lang3.StringUtils
class org.apache.qpid.jms.JmsConnectionFactory
class org.quartz.CronScheduleBuilder
class org.quartz.JobBuilder
class org.quartz.JobDetail
class org.quartz.JobExecutionContext
class org.quartz.JobExecutionException
class org.quartz.Scheduler
class org.quartz.SchedulerException
class org.quartz.SimpleScheduleBuilder
class org.quartz.Trigger
class org.quartz.TriggerBuilder
class org.slf4j.Logger
class org.slf4j.LoggerFactory
class org.springframework.amqp.core.Binding
class org.springframework.amqp.core.BindingBuilder
class org.springframework.amqp.core.Queue
class org.springframework.amqp.core.TopicExchange
class org.springframework.amqp.support.converter.Jackson2JsonMessageConverter
class org.springframework.amqp.support.converter.MessageConverter
class org.springframework.boot.SpringApplication
class org.springframework.dao.PermissionDeniedDataAccessException
class org.springframework.data.domain.Sort
class org.springframework.http.HttpStatusCode
class org.springframework.http.MediaType
class org.springframework.http.ResponseEntity
class org.springframework.scheduling.quartz.SchedulerFactoryBean
class org.springframework.security.authentication.AuthenticationManager
class org.springframework.security.authentication.AuthenticationProvider
class org.springframework.security.authentication.UsernamePasswordAuthenticationToken
class org.springframework.security.authentication.dao.DaoAuthenticationProvider
class org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration
class org.springframework.security.config.annotation.web.builders.HttpSecurity
class org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer
class org.springframework.security.config.http.SessionCreationPolicy
class org.springframework.security.core.AuthenticationException
class org.springframework.security.core.GrantedAuthority
class org.springframework.security.core.authority.SimpleGrantedAuthority
class org.springframework.security.core.context.SecurityContext
class org.springframework.security.core.context.SecurityContextHolder
class org.springframework.security.core.userdetails.UsernameNotFoundException
class org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder
class org.springframework.security.crypto.password.PasswordEncoder
class org.springframework.security.web.SecurityFilterChain
class org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter
class org.springframework.security.web.authentication.WebAuthenticationDetailsSource
class org.springframework.web.cors.CorsConfiguration
class org.springframework.web.filter.OncePerRequestFilter
class tad.blps.BlipsApplication
class tad.blps.DTO.AccountDTO
class tad.blps.DTO.FileDTO
class tad.blps.DTO.PaymentDTO
class tad.blps.DTO.TokenDTO
class tad.blps.RabbitMQ.Receiver
class tad.blps.RabbitMQ.Sender
class tad.blps.SecurityDetail.UserDetailImpl
class tad.blps.SecurityDetail.UserDetailServiceImpl
class tad.blps.config.MQTTConfig
class tad.blps.config.SecurityConfiguration
class tad.blps.config.TransactionConfig
class tad.blps.controller.authController
class tad.blps.controller.fileController
class tad.blps.controller.messgeController
class tad.blps.controller.paymentController
class tad.blps.controller.userController
class tad.blps.entity.File
class tad.blps.entity.Payment
class tad.blps.entity.Role
class tad.blps.entity.User
class tad.blps.filters.CORSFilter
class tad.blps.filters.JwtTokenAuthFilter
class tad.blps.scheduler.JobContainer
class tad.blps.scheduler.detail.DeleteFileDetail
class tad.blps.scheduler.jobs.DeleteFileJob
class tad.blps.scheduler.triggers.DeleteFileTrigger
class tad.blps.services.AuthenticationService
class tad.blps.services.FileService
class tad.blps.services.PaymentService
class tad.blps.services.RoleService
class tad.blps.services.UserService
class tad.blps.utils.AuthEntryPointJwt
class tad.blps.utils.BasicAuthUtil
@enduml